import 'package:meta/meta.dart';

/// Base class for all exceptions in this library
abstract class MySQLException implements Exception {
  const MySQLException(this.message, this.stackTrace);

  final String message;
  final StackTrace stackTrace;

  String get _prefix;

  @override
  String toString() {
    return '$_prefix: $message\n$stackTrace';
  }
}

/// Class for errors generated by mysql server itself
///
/// Extends [MySQLException]. MySQL error code can be read from [errorCode]
class MySQLServerException extends MySQLException {
  MySQLServerException(super.message, super.stackTrace, this.errorCode, [this.query, this.params]);

  /// MySQL server error code
  final int errorCode;

  final String? query;

  final Map<String, dynamic>? params;

  @override
  String toString() {
    final StringBuffer stringBuffer = StringBuffer('$_prefix [$errorCode]: $message\n$stackTrace');
    if (query != null) {
      stringBuffer.write('\nQuery: $query');
    }
    if (params != null) {
      stringBuffer.write('\nParams: $params');
    }

    return stringBuffer.toString();
  }

  @override
  String get _prefix => 'MySQLServerException';
}

/// Class for exceptions generated by this library
///
/// Extends [MySQLException]
class MySQLClientException extends MySQLException {
  @protected
  const MySQLClientException(
    String? message,
    StackTrace stackTrace, {
    required this.code,
  }) : super(message ?? '', stackTrace);

  MySQLClientException.timeout({required Duration duration, String? message, StackTrace? stackTrace})
      : code = MySQLClientExceptionCode.timeout,
        super(message ?? 'Operation timed out after: $duration', stackTrace ?? StackTrace.current);

  MySQLClientException.unexpectedState({required String message, StackTrace? stackTrace})
      : code = MySQLClientExceptionCode.unexpectedState,
        super(message, stackTrace ?? StackTrace.current);

  MySQLClientException.unexpectedPayload({required String request, StackTrace? stackTrace})
      : code = MySQLClientExceptionCode.unexpectedPayload,
        super('Unexpected payload received in response to $request request', stackTrace ?? StackTrace.current);

  MySQLClientException.unexpectedPacket({required String message, StackTrace? stackTrace})
      : code = MySQLClientExceptionCode.unexpectedPacket,
        super(message, stackTrace ?? StackTrace.current);

  MySQLClientException.connectionClosed({String? message, StackTrace? stackTrace})
      : code = MySQLClientExceptionCode.closedConnection,
        super(message ?? 'Cannot execute operation, connection is closed', stackTrace ?? StackTrace.current);

  final MySQLClientExceptionCode code;

  @override
  String get _prefix => 'MySQLClientException';
}

enum MySQLClientExceptionCode {
  brokenConnection,
  closedConnection,
  unexpectedState,
  unexpectedPayload,
  unexpectedPacket,
  unsupported,
  invalidArgument,
  timeout,
  protocolError,
  unknown,
}

/// Class for mysql protocol specific exceptions
///
/// Extends [MySQLClientException]
class MySQLProtocolException extends MySQLClientException {
  MySQLProtocolException(String message)
      : super(message, StackTrace.current, code: MySQLClientExceptionCode.protocolError);

  @override
  String get _prefix => 'MySQLProtocolException';
}
